version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: static-server
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
